name: 'Android Observability'

on:
    push:
        branches: ['main']
        paths:
            - 'sdk/@launchdarkly/observability-android/**'
            - '.github/workflows/android-plugin.yml'
    pull_request:
        types: [opened, synchronize]
        paths:
            - 'sdk/@launchdarkly/observability-android/**'
            - '.github/workflows/android-plugin.yml'

concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
    test:
        name: Unit Tests
        runs-on: ubuntu-22.04-8core-32gb
        defaults:
            run:
                working-directory: ./sdk/@launchdarkly/observability-android
        steps:
            - uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: 17

            - name: Set up Android SDK
              uses: android-actions/setup-android@v3

            - name: Run unit tests
              run: ./gradlew :lib:testDebugUnitTest

            - name: Upload test reports
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: android-unit-test-results
                  path: sdk/@launchdarkly/observability-android/**/build/test-results/**/TEST-*.xml
                  retention-days: 7
