name: 'Android E2E App Tests'

on:
    push:
        branches: ['main']
        paths:
            - 'e2e/android/**'
            - 'sdk/@launchdarkly/observability-android/**'
            - '.github/workflows/android-e2e.yml'
    pull_request:
        types: [opened, synchronize]
        paths:
            - 'e2e/android/**'
            - 'sdk/@launchdarkly/observability-android/**'
            - '.github/workflows/android-e2e.yml'

permissions:
    contents: read

concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
    test:
        name: E2E Tests
        runs-on: ubuntu-22.04-8core-32gb
        defaults:
            run:
                working-directory: ./e2e/android
        steps:
            - uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: 17

            - name: Set up Android SDK
              uses: android-actions/setup-android@9fc6c4e9069bf8d3d10b2204b1fb8f6ef7065407 # v3.2.2 commit SHA - https://github.com/android-actions/setup-android/releases/tag/v3.2.2

            - name: Run unit tests
              run: ./gradlew :app:testComposeDebugUnitTest

            - name: Upload test reports
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: android-e2e-unit-test-results
                  path: e2e/android/**/build/test-results/**/TEST-*.xml
                  retention-days: 7
